version: "3.8"

services:
  api:
    container_name: gc-backend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./server:/app
    command: ./docker-entrypoint.sh
    environment:
      DEBUG: app:WWW,app:Telnyx,app:Genesys
  client:
    container_name: gc-frontend
    restart: always
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - 4000:80
    volumes:
      - /app/node_modules
      - ./client:/app
